### ISSUE TITLE
Missing resources referenced from main.c

### ISSUE THREAD

**Issue by lundstroem** [BeratE/SoftwareRasterizer#1]
Hello! I thought I'd try to get this to run, however there seems to be references to some missing assets in the repo, namely:
`SRM_LoadMesh(&mesh, "/home/berat/Projects/assets/Models/sign.obj");`
and
`_image.values = stbi_load("/home/berat/Projects/assets/Textures/sign.png",`

also, there is a file duplicate to srerasterizer called srerasterzer.c which I assume is not used.

Let me know if I've missed something, cheers! :)

**Comment by BeratE** [comment]
Hello,
The main file just performs some tests and showcases the use of the framework. It doesn't contain anything meaningful, to be honest. 
The filenames are just absolute paths to a mesh file and a texture image. I honestly don't have them anymore (or lost in some backup drive).  
So if you have a mesh and a texture just replace the path names. That should do it.

It's been a while so I'd have to setup the project on my machine and see if I can implement some meaningful test cases, and a proper model loader.

**Comment by lundstroem** [comment]
ok, I'll try to find some generic mesh and texture to use instead. Thanks!
